version: "3.8"

services:
  odoo:
    image: odoo:18.0
    container_name: odoo
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=host.docker.internal
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
